// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2025-11-06T15:28:19.836Z

import type { FiletypeParserOptions } from "./types"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const javascript_highlights = "./assets/javascript/highlights.scm"
const javascript_language = "./assets/javascript/tree-sitter-javascript.wasm"
const typescript_highlights = "./assets/typescript/highlights.scm"
const typescript_language = "./assets/typescript/tree-sitter-typescript.wasm"
const markdown_highlights = "./assets/markdown/highlights.scm"
const markdown_language = "./assets/markdown/tree-sitter-markdown.wasm"
const markdown_injections = "./assets/markdown/injections.scm"
const markdown_inline_highlights = "./assets/markdown_inline/highlights.scm"
const markdown_inline_language = "./assets/markdown_inline/tree-sitter-markdown_inline.wasm"
const zig_highlights = "./assets/zig/highlights.scm"
const zig_language = "./assets/zig/tree-sitter-zig.wasm"

const moduleDir = dirname(fileURLToPath(import.meta.url))

// Cached parsers to avoid re-resolving paths on every call
let _cachedParsers: FiletypeParserOptions[] | undefined

export function getParsers(): FiletypeParserOptions[] {
  if (!_cachedParsers) {
    _cachedParsers = [
      {
        filetype: "javascript",
        queries: {
          highlights: [resolve(moduleDir, javascript_highlights)],
        },
        wasm: resolve(moduleDir, javascript_language),
      },
      {
        filetype: "typescript",
        queries: {
          highlights: [resolve(moduleDir, typescript_highlights)],
        },
        wasm: resolve(moduleDir, typescript_language),
      },
      {
        filetype: "markdown",
        queries: {
          highlights: [resolve(moduleDir, markdown_highlights)],
          injections: [resolve(moduleDir, markdown_injections)],
        },
        wasm: resolve(moduleDir, markdown_language),
        injectionMapping: {
          nodeTypes: {
            inline: "markdown_inline",
            pipe_table_cell: "markdown_inline",
          },
          infoStringMap: {
            javascript: "javascript",
            js: "javascript",
            typescript: "typescript",
            ts: "typescript",
            markdown: "markdown",
            md: "markdown",
          },
        },
      },
      {
        filetype: "markdown_inline",
        queries: {
          highlights: [resolve(moduleDir, markdown_inline_highlights)],
        },
        wasm: resolve(moduleDir, markdown_inline_language),
      },
      {
        filetype: "zig",
        queries: {
          highlights: [resolve(moduleDir, zig_highlights)],
        },
        wasm: resolve(moduleDir, zig_language),
      },
    ]
  }
  return _cachedParsers
}
